EXECUTE_PROCESS(COMMAND mktemp -d OUTPUT_VARIABLE WORK_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
FILE(READ "${PACKAGING_DIR}/settings.yml" TEMPLATE)
FILE(WRITE "${WORK_DIR}/source.yml" "host: localhost\nuser: repl\npassword: test-secret\n")
FILE(WRITE "${WORK_DIR}/replica.yml" "listen_port: 3307\n")
FILE(CHMOD "${WORK_DIR}/source.yml" "${WORK_DIR}/replica.yml" PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ)
SET(FAILURE "")
FOREACH(SIZE IN ITEMS 1M 2M 1P)
    # Match the final max_size independently of comments between cache keys.
    STRING(FIND "${TEMPLATE}" "\ncache:" CACHE_START)
    STRING(SUBSTRING "${TEMPLATE}" 0 ${CACHE_START} PREFIX)
    STRING(SUBSTRING "${TEMPLATE}" ${CACHE_START} -1 CACHE_TEXT)
    STRING(REGEX REPLACE "max_size: [^\n]+" "max_size: ${SIZE}" CACHE_TEXT "${CACHE_TEXT}")
    FILE(WRITE "${WORK_DIR}/settings.yml" "${PREFIX}${CACHE_TEXT}")
    EXECUTE_PROCESS(COMMAND "${BINARY}" --validate-config --config "${WORK_DIR}/settings.yml"
        RESULT_VARIABLE RC OUTPUT_VARIABLE OUT ERROR_VARIABLE ERR)
    IF(SIZE STREQUAL "1M")
        IF(NOT RC EQUAL 1 OR NOT ERR MATCHES "cache.max_size: must be at least 2M")
            STRING(APPEND FAILURE "1M: rc=${RC}, ${ERR}\n")
        ENDIF()
    ELSEIF(SIZE STREQUAL "2M")
        IF(NOT RC EQUAL 0 OR ERR MATCHES "warning: cache.max_size")
            STRING(APPEND FAILURE "2M: rc=${RC}, ${ERR}\n")
        ENDIF()
    ELSE()
        STRING(FIND "${ERR}" "warning: cache.max_size (1125899906842624 bytes) is larger than this host's physical memory (" WARNING_AT)
        IF(NOT RC EQUAL 0 OR WARNING_AT EQUAL -1)
            STRING(APPEND FAILURE "1P: rc=${RC}, ${ERR}\n")
        ENDIF()
    ENDIF()
ENDFOREACH()
FILE(REMOVE_RECURSE "${WORK_DIR}")
IF(NOT FAILURE STREQUAL "")
    MESSAGE(FATAL_ERROR "${FAILURE}")
ENDIF()
