ADD_LIBRARY(bs-cache STATIC cEventCache.cpp)
FIND_PACKAGE(Threads REQUIRED)
TARGET_LINK_LIBRARIES(bs-cache PUBLIC bs-warnings Threads::Threads)
ADD_HEADER_CHECK(bs-cache-hc
    "${BINLOG_STREAMER_INCLUDE_DIR}/cache" "${BINLOG_STREAMER_INCLUDE_DIR}")
IF(BUILD_TESTING)
    ADD_SUBDIRECTORY(tests)
ENDIF()
