#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    if [ -x /usr/bin/deb-systemd-helper ]; then
        deb-systemd-helper purge binlog-streamer.service >/dev/null || true
    fi
fi

if [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
