# Included from the top-level CMakeLists.txt before PROJECT(): PROJECT_SOURCE_DIR
# is not set yet, and CMAKE_CURRENT_SOURCE_DIR is the project root.
SET(VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/VERSION")
SET_PROPERTY(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${VERSION_FILE}")
FILE(STRINGS "${VERSION_FILE}" VERSION_LINES)

FOREACH(COMPONENT MAJOR MINOR PATCH)
    SET(COMPONENT_LINES "${VERSION_LINES}")
    LIST(FILTER COMPONENT_LINES INCLUDE REGEX "^BS_${COMPONENT}[ \t]*=")
    LIST(LENGTH COMPONENT_LINES COMPONENT_COUNT)
    IF(NOT COMPONENT_COUNT EQUAL 1)
        MESSAGE(FATAL_ERROR "VERSION must define BS_${COMPONENT} exactly once")
    ENDIF()
    IF(NOT "${COMPONENT_LINES}" MATCHES "^BS_${COMPONENT}[ \t]*=[ \t]*([0-9]+)[ \t]*$")
        MESSAGE(FATAL_ERROR "BS_${COMPONENT} must be a non-negative integer")
    ENDIF()
    SET(VERSION_${COMPONENT} "${CMAKE_MATCH_1}")
ENDFOREACH()

SET(BINLOG_STREAMER_VERSION
    "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
